[dependencies]
ast = "alicesaidhi/conch-ast@0.2.1"
compiler = "alicesaidhi/conch-compiler@0.2.2"
intel = "alicesaidhi/conch-analysis@0.2.1"
types = "alicesaidhi/conch-types@0.2.1"
vm = "alicesaidhi/conch-vm@0.2.1"

[package]
exclude = [
    "pesde.toml",
    "pesde.lock",
    "src",
    "roblox_packages",
    "luau_packages",
]
include = ["/dist"]
name = "alicesaidhi/conch"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.2.4"
